<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.2.master at 2015-09-29 13:57:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	namespace Onphp\Log\Examples;
	
	final class LogDAO extends \Onphp\Log\Examples\AutoLogDAO
	{
		// last chance for customization
	}
?>