<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.2.master at 2015-09-29 13:57:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	$schema = new \Onphp\DBSchema();
	
	$schema->
		addTable(
			\Onphp\DBTable::create('log')->
			addColumn(
				\Onphp\DBColumn::create(
					\Onphp\DataType::create(\Onphp\DataType::INTEGER)->
					setNull(false),
					'id'
				)->
				setPrimaryKey(true)->
				setAutoincrement(true)
			)->
			addColumn(
				\Onphp\DBColumn::create(
					\Onphp\DataType::create(\Onphp\DataType::TIMESTAMP)->
					setNull(false),
					'date'
				)
			)->
			addColumn(
				\Onphp\DBColumn::create(
					\Onphp\DataType::create(\Onphp\DataType::INTEGER)->
					setNull(false),
					'level'
				)
			)->
			addColumn(
				\Onphp\DBColumn::create(
					\Onphp\DataType::create(\Onphp\DataType::VARCHAR)->
					setNull(false)->
					setSize(5000),
					'message'
				)
			)
		);
	
?>