<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2015-09-30 00:26:22                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class Log extends AutoLog implements Prototyped, DAOConnected
	{
		/**
		 * @return Log
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return LogDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('LogDAO');
		}
		
		/**
		 * @return ProtoLog
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoLog');
		}
		
		// your brilliant stuff goes here
	}
?>