<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.2.master at 2015-09-29 13:57:40                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	namespace Onphp\Log\Examples;
	
	final class Log extends \Onphp\Log\Examples\AutoLog implements \Onphp\Prototyped, \Onphp\DAOConnected
	{
		// your brilliant stuff goes here
	}
?>