<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2015-09-30 00:26:22                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ProtoLog extends AutoProtoLog {/*_*/}
?>