<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2015-09-30 00:26:22                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoLogDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'log';
		}
		
		public function getObjectName()
		{
			return 'Log';
		}
		
		public function getSequence()
		{
			return 'log_id';
		}
	}
?>