<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2015-09-30 00:26:22                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoLog extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Log', 4, true, true, false, null, null),
				'date' => LightMetaProperty::fill(new LightMetaProperty(), 'date', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'level' => LightMetaProperty::fill(new LightMetaProperty(), 'level', null, 'integer', null, 4, true, true, false, null, null),
				'message' => LightMetaProperty::fill(new LightMetaProperty(), 'message', null, 'string', null, 5000, true, true, false, null, null)
			);
		}
	}
?>