<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.2.master at 2015-09-29 13:57:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	namespace Onphp\Log\Examples;
	
	abstract class AutoProtoLog extends \Onphp\AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => \Onphp\LightMetaProperty::fill(new \Onphp\LightMetaProperty(), 'id', null, 'integerIdentifier', '\Onphp\Log\Examples\Log', 4, true, true, false, null, null),
				'date' => \Onphp\LightMetaProperty::fill(new \Onphp\LightMetaProperty(), 'date', null, 'timestamp', '\Onphp\Timestamp', null, true, true, false, null, null),
				'level' => \Onphp\LightMetaProperty::fill(new \Onphp\LightMetaProperty(), 'level', null, 'integer', null, 4, true, true, false, null, null),
				'message' => \Onphp\LightMetaProperty::fill(new \Onphp\LightMetaProperty(), 'message', null, 'string', null, 5000, true, true, false, null, null)
			);
		}
	}
?>