<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.2.master at 2015-09-29 13:57:40                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	namespace Onphp\Log\Examples;
	
	abstract class AutoLog extends \Onphp\IdentifiableObject
	{
		protected $date = null;
		protected $level = null;
		protected $message = null;
		
		/**
		 * @return \Onphp\Log\Examples\Log
		**/
		public static function create()
		{
			return new static;
		}
		
		/**
		 * @return \Onphp\Log\Examples\LogDAO
		**/
		public static function dao()
		{
			return \Onphp\Singleton::getInstance('\Onphp\Log\Examples\LogDAO');
		}
		
		/**
		 * @return \Onphp\Log\Examples\ProtoLog
		**/
		public static function proto()
		{
			return \Onphp\Singleton::getInstance('\Onphp\Log\Examples\ProtoLog');
		}
		
		/**
		 * @return \Onphp\Timestamp
		**/
		public function getDate()
		{
			return $this->date;
		}
		
		/**
		 * @return \Onphp\Log\Examples\Log
		**/
		public function setDate(\Onphp\Timestamp $date)
		{
			$this->date = $date;
			
			return $this;
		}
		
		/**
		 * @return \Onphp\Log\Examples\Log
		**/
		public function dropDate()
		{
			$this->date = null;
			
			return $this;
		}
		
		public function getLevel()
		{
			return $this->level;
		}
		
		/**
		 * @return \Onphp\Log\Examples\Log
		**/
		public function setLevel($level)
		{
			$this->level = $level;
			
			return $this;
		}
		
		public function getMessage()
		{
			return $this->message;
		}
		
		/**
		 * @return \Onphp\Log\Examples\Log
		**/
		public function setMessage($message)
		{
			$this->message = $message;
			
			return $this;
		}
	}
?>