<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2015-09-30 00:26:22                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoLog extends IdentifiableObject
	{
		protected $date = null;
		protected $level = null;
		protected $message = null;
		
		/**
		 * @return Timestamp
		**/
		public function getDate()
		{
			return $this->date;
		}
		
		/**
		 * @return Log
		**/
		public function setDate(Timestamp $date)
		{
			$this->date = $date;
			
			return $this;
		}
		
		/**
		 * @return Log
		**/
		public function dropDate()
		{
			$this->date = null;
			
			return $this;
		}
		
		public function getLevel()
		{
			return $this->level;
		}
		
		/**
		 * @return Log
		**/
		public function setLevel($level)
		{
			$this->level = $level;
			
			return $this;
		}
		
		public function getMessage()
		{
			return $this->message;
		}
		
		/**
		 * @return Log
		**/
		public function setMessage($message)
		{
			$this->message = $message;
			
			return $this;
		}
	}
?>